### PR TITLE
Adding Alienware 15 r3 support

### PR DESCRIPTION
**Pull request by DieracDelta**
This should add in support for the alienware 15 r3. The method for switching colors has changed a bit, as the red and green are now separate arguments. I haven't thoroughly tested beyond just rudimentary color switching.

### CODE REVIEW

**Comment by arcangeli** [comment]
Hi, can you add 0x529 (13r3oled) at line 548?
Now i can change all color on my 13r3oled.
Thanks

**Comment by DieracDelta** [comment]
This should be refactored a bit more (e.g. rename method, maybe add an extra attribute to AlienFxTypes to indicate which method should be used). For now, I just pushed that one change.

**Comment by erlkonig** [comment]
I agree that this will need refactoring eventually, but it's a good starting point.  Merging.

**Comment by erlkonig** [comment]
And thanks for your time and efforts :-)

**Pull request merged**
